### ISSUE TITLE
[Q&A] Kubernetes as backend?

### ISSUE THREAD

**Issue by Byron-TW** [charleskorn/batect#2]
What would it take to take (parts) of Batect to use kubernetes as runtime?

That could be useful if people wanted to escape their constrained workstation resources and run in the cloud.

Something relevant or inspiring might be [argo](https://github.com/argoproj/argo).

**Comment by charleskorn** [comment]
Hey @Byron-TW, thanks for the question. 

(@Byron-TW contacted me offline about this, I'm sharing my original response from that conversation below.)

In theory, it shouldn’t be too hard to plug another runner into batect so that things are launched on Kubernetes instead of directly on Docker. 

Practically, it’s a bit different :) These are some of the issues I foresee:
* there isn’t a clean separation in the code between the process of orchestrating containers and the thing that they’re running on (eg. Docker) - everything is fairly tied to the Docker way of thinking about and doing things
* mounting a local directory would be a little tricky - you’d have to package up the files or folder in question and deploy them alongside the image, and there would be work in bringing back any new files to the local workspace (eg. if the build process inside the pod creates some build artifacts like a JAR file, you’d either have to archive that JAR as part of the build process or somehow pull the newly created files back into the local filesystem)
* …and if you wanted to support syncing changes to the local filesystem to the pod in realtime (to enable scenarios like continuous unit testing), that would be another order of magnitude harder again
* ditto for port mappings - if you want to run your app remotely and then interact with it locally, there would be some work in making that work seamlessly

If you’re just thinking of using Kubernetes in CI scenarios (but local Docker for local development scenarios), it should be feasible, since those last two points aren’t so relevant in that situation. Docker-in-pods might help you avoid having to change batect, but mounting directories from Docker-in-pods gets tricky quickly.

I hadn’t seen Argo before, thanks for passing that along. Looks really interesting, and not just for build scenarios but also more complex batch processing-style tasks.

**Comment by charleskorn** [comment]
While this is something I'd be interested in exploring in the future, I have no immediate plans to act on this, so I'm going to close this issue.

If anyone has any thoughts on this topic, please feel free to continue the discussion here.
