### ISSUE TITLE
Windows containers

### ISSUE THREAD

**Issue by DamianBis** [charleskorn/batect#275]
when running with windows containers i get errors.

"Error: An unexpected exception occurred during execution.
During execution of step of kind 'CreateTaskNetworkStep': java.net.SocketTimeoutException: Read timed out"

Based off of reading the documentation it's not explicitly there, but it seems implied that windows containers aren't supported.

Are there any plans for adding support for windows containers to batect? I imagine that most of what's being run by batect are docker commands so windows/linux containers shouldn't make much of a difference?

**Comment by charleskorn** [comment]
Hey @DamianBis, thanks for the feedback. You're correct - Windows containers aren't supported, and that isn't explicitly called out in the docs. I'll add something to clarify this.

There are no plans to support Windows containers at the moment - given the relatively small number of people that use Windows containers it's not a priority, but I'd be happy for someone to contribute this (and I assume it wouldn't be too difficult to do, because as you say, batect is just using the Docker API under the hood).

At the very least, that error message could be clearer - I'll clarify that as well.

**Comment by charleskorn** [comment]
Good news - turns out this isn't hard to implement so I've added support for Windows containers and this will be part of the next release (which should be out shortly). Thanks again for your feedback @DamianBis!
