### ISSUE TITLE
Hot reload / file watch functionality

### ISSUE THREAD

**Issue by ineffyble** [charleskorn/batect#47]
It would be neat if I could set an option, and have Batect automatically re-build and run the current task on file change.

**Comment by charleskorn** [comment]
Hi @ineffyble, thanks for the suggestion. 

How would you like this to behave? I'm imagining something like a `--watch` flag on the command line (so it would be `./batect --watch build`), and it would look for changes in the mounted directories. 

And I'm imagining a need to be able to exclude certain directories (eg. don't trigger a rebuild just because the build produced the artifact in a mounted directory - otherwise you'd end up in an endless loop) - would you want to do this in the configuration file or on the command line as well?

Given there are many other tools out there that could be used by batect (either inside a container or outside), I'm not going to make it a priority, but I will add it to the backlog for inclusion in the future.

**Comment by charleskorn** [comment]
I'm going to close this as won't fix - given the diversity of requirements, and the many tools already out there that could do this much better and work in conjunction with batect, this doesn't feel like a great fit for batect to implement right now.
